version: '3.4'

services:
  hrm.authen.apilayer:
    image: ${DOCKER_REGISTRY-}hrmauthenapilayer
    build:
      context: .
      dockerfile: Hrm.Authen.APILayer/Dockerfile

  hrm.interview.apilayer:
    image: ${DOCKER_REGISTRY-}hrminterviewapilayer
    build:
      context: .
      dockerfile: Hrm.Interview.APILayer/Dockerfile


  hrm.onboard.apilayer:
    image: ${DOCKER_REGISTRY-}hrmonboardapilayer
    build:
      context: .
      dockerfile: Hrm.Onboard.APILayer/Dockerfile


  hrm.recruitment.apilayer:
    image: ${DOCKER_REGISTRY-}hrmrecruitmentapilayer
    build:
      context: .
      dockerfile: Hrm.Recruitment.APILayer/Dockerfile

